# sentra_brain_api/features/llm_proxy/models.py

from datetime import datetime
from typing import List, Optional, Union, Literal, Dict, Any
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: Literal["system", "user", "assistant"] = Field(..., description="The role of the message author")
    content: str = Field(..., description="The content of the message")


class ChatCompletionRequest(BaseModel):
    model: str = Field(..., description="ID of the model to use")
    messages: List[ChatMessage] = Field(..., min_length=1, description="A list of messages comprising the conversation so far")
    stream: Optional[bool] = Field(False, description="Whether to stream back partial progress")
    temperature: Optional[float] = Field(1.0, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, description="Maximum number of tokens to generate")
    top_p: Optional[float] = Field(1.0, ge=0.0, le=1.0, description="Nucleus sampling parameter")


class ChatCompletionChoice(BaseModel):
    index: int = Field(..., description="The index of the choice")
    message: ChatMessage = Field(..., description="The message generated by the model")
    finish_reason: Optional[Literal["stop", "length", "content_filter"]] = Field(
        None, description="The reason the model stopped generating tokens"
    )


class ChatCompletionUsage(BaseModel):
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt")
    completion_tokens: int = Field(..., description="Number of tokens in the completion")
    total_tokens: int = Field(..., description="Total number of tokens used")


class ChatCompletionResponse(BaseModel):
    id: str = Field(..., description="A unique identifier for the chat completion")
    object: Literal["chat.completion"] = Field("chat.completion", description="The object type")
    created: int = Field(..., description="The Unix timestamp when the completion was created")
    model: str = Field(..., description="The model used for the completion")
    choices: List[ChatCompletionChoice] = Field(..., description="A list of completion choices")
    usage: ChatCompletionUsage = Field(..., description="Usage statistics for the completion request")


class ChatCompletionChunk(BaseModel):
    id: str = Field(..., description="A unique identifier for the chat completion")
    object: Literal["chat.completion.chunk"] = Field("chat.completion.chunk", description="The object type")
    created: int = Field(..., description="The Unix timestamp when the chunk was created")
    model: str = Field(..., description="The model used for the completion")
    choices: List[Dict[str, Any]] = Field(..., description="A list of completion choices")