from typing import Protocol, TypeVar, Generic, Optional
from uuid import UUID

T = TypeVar('T')

class IBaseRepository(Protocol, Generic[T]):
    def get(self, id: UUID) -> Optional[T]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[T]: ...
    def filter_by(self, limit: int = 100, offset: int = 0, **kwargs) -> list[T]: ...
    def create(self, obj: T) -> T: ...
    def update(self, obj: T) -> T: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
