from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.chat_settings import ChatSettingsEntity

class IChatSettingsRepository(Protocol):
    def get(self, id: UUID) -> Optional[ChatSettingsEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[ChatSettingsEntity]: ...
    def create(self, obj: ChatSettingsEntity) -> ChatSettingsEntity: ...
    def update(self, obj: ChatSettingsEntity) -> ChatSettingsEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...