from typing import Any, Protocol, Optional
from uuid import UUID
from sentra.domain.entities.conversation_entity import ConversationEntity

class IConversationSQLRepository(Protocol):
    """Persistence for conversation metadata."""
    def get(self, id: UUID) -> Optional[ConversationEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[ConversationEntity]: ...
    def create(self, obj: ConversationEntity) -> ConversationEntity: ...
    def update(self, obj: ConversationEntity) -> ConversationEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...
    def get_conversations_by_user_id(self, user_id: UUID) -> list[ConversationEntity]: ...
    def update_title(self, conversation_id: UUID, title: str) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...

class IConversationNoSQLRepository(Protocol):
    """Persistence for conversation runtime data (messages, metadata mirror)."""

    def create_conversation(self, conversation_id: UUID, user_id: UUID, **fields: Any) -> dict: ...
    def get_conversation_by_id(self, conversation_id: UUID, user_id: UUID) -> Optional[dict]: ...
    def update_conversation(self, conversation_id: UUID, updates: dict) -> int: ...
    def delete_conversation(self, conversation_id: UUID, user_id: UUID) -> None: ...