from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.conversation_entity import ConversationEntity

class IConversationRepository(Protocol):
    def get(self, id: UUID) -> Optional[ConversationEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[ConversationEntity]: ...
    def create(self, obj: ConversationEntity) -> ConversationEntity: ...
    def update(self, obj: ConversationEntity) -> ConversationEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...
    def get_conversations_by_user_id(self, user_id: UUID) -> list[ConversationEntity]: ...
    def update_title(self, conversation_id: UUID, title: str) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...
