from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.document_entity import DocumentEntity

class IDocumentRepository(Protocol):
    def get(self, id: UUID) -> Optional[DocumentEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[DocumentEntity]: ...
    def create(self, obj: DocumentEntity) -> DocumentEntity: ...
    def update(self, obj: DocumentEntity) -> DocumentEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def list_by_source(self, knowledge_source_id: Optional[UUID] = None, limit: int = 100, offset: int = 0) -> list[DocumentEntity]: ...
    def count_by_source(self, knowledge_source_id: Optional[UUID] = None) -> int: ...
    def update_status(self, document_id: UUID, status, error: Optional[str] = None, status_message: Optional[str] = None, chunks_count: Optional[int] = None) -> Optional[DocumentEntity]: ...
    def list_by_user_or_source(self, user_id: UUID, knowledge_source_id: Optional[UUID] = None, limit: int = 100, offset: int = 0) -> list[DocumentEntity]: ...
    def count_by_user_or_source(self, user_id: UUID, knowledge_source_id: Optional[UUID] = None) -> int: ...
    def update_markdown_info(self, document_id: UUID, path: str, size: int, sha256: str) -> None: ...
