from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.knowledge_source_entity import KnowledgeSourceEntity

class IKnowledgeSourceRepository(Protocol):
    def get(self, id: UUID) -> Optional[KnowledgeSourceEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[KnowledgeSourceEntity]: ...
    def create(self, obj: KnowledgeSourceEntity) -> KnowledgeSourceEntity: ...
    def update(self, obj: KnowledgeSourceEntity) -> KnowledgeSourceEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def list_by_user(self, created_by: UUID, limit: int = 100, offset: int = 0) -> list[KnowledgeSourceEntity]: ...
    def count_by_user(self, created_by: UUID) -> int: ...
    def get_folder_sources(self, auto_index_only: bool = True) -> list[KnowledgeSourceEntity]: ...


