from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.organization_entity import OrganizationEntity

class IOrganizationRepository(Protocol):
    def get(self, id: UUID) -> Optional[OrganizationEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[OrganizationEntity]: ...
    def create(self, obj: OrganizationEntity) -> OrganizationEntity: ...
    def update(self, obj: OrganizationEntity) -> OrganizationEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...