from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.session_entity import SessionEntity

class ISessionRepository(Protocol):
    def get(self, id: UUID) -> Optional[SessionEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[SessionEntity]: ...
    def create(self, obj: SessionEntity) -> SessionEntity: ...
    def update(self, obj: SessionEntity) -> SessionEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...
    def get_sessions_by_user_id(self, user_id: UUID) -> list[SessionEntity]: ...
    def update_title(self, session_id: UUID, title: str) -> None: ...
    def create_with_user_id(self, user_id: UUID) -> UUID: ...
