from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.system_settings import SystemSettingsEntity

class ISystemSettingsRepository(Protocol):
    def get(self, id: UUID) -> Optional[SystemSettingsEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[SystemSettingsEntity]: ...
    def create(self, obj: SystemSettingsEntity) -> SystemSettingsEntity: ...
    def update(self, obj: SystemSettingsEntity) -> SystemSettingsEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...