from typing import Protocol, Optional
from uuid import UUID
from sentra.domain.entities.user_entity import UserEntity

class IUserRepository(Protocol):
    def get(self, id: UUID) -> Optional[UserEntity]: ...
    def get_all(self, limit: int = 100, offset: int = 0) -> list[UserEntity]: ...
    def create(self, obj: UserEntity) -> UserEntity: ...
    def update(self, obj: UserEntity) -> UserEntity: ...
    def delete(self, id: UUID, soft: bool = True) -> None: ...
    def get_by_username(self, username: str) -> Optional[UserEntity]: ...
    def get_by_email(self, email: str) -> Optional[UserEntity]: ...
