services:
  sentra-web:
    build:
      context: ../frontends/sentra-web    
    command: ["npm", "run", "dev:inspect"]
    image: sentra-web:dev
    container_name: sentra-web
    ports:
      - "3100:3100"   # App
      - "3129:9229"   # Node.js Inspect
    volumes:
      - ../frontends/sentra-web:/app
      - /app/node_modules
    networks:
      - sentrabrain-dev-net
    env_file:
      - ../frontends/sentra-web/.env

  sentra-api:
    build:
      context: ../
      dockerfile: services/sentra-api/Dockerfile
    image: sentra-api:dev
    container_name: sentra-api
    ports:
      - "8100:8100"
      - "5678:5678"
      - "8080:8080"   # Metrics port
    volumes:
      - ../services/sentra-api:/app
      - ../packages/sentra-domain:/packages/sentra-domain
      - ../packages/sentra-infra:/packages/sentra-infra
      - ../packages/sentra-runtime:/packages/sentra-runtime
      - ${HOME}/sentra-knowledge:/mnt/sentra_knowledge:rw
    networks:
      - sentrabrain-dev-net
    env_file:
      - ../services/sentra-api/.env
    depends_on:
      - sentra-sql-db
      - sentra-nosql-db
      - rabbitmq

  sentra-mcp:
    build:
      context: ../
      dockerfile: services/sentra-mcp/Dockerfile
    image: sentra-mcp:dev
    container_name: sentra-mcp
    ports:
      - "8200:8200"
      - "5681:5681"   # Python debugpy
    volumes:
      - ../services/sentra-mcp:/app
      - ../packages/sentra-infra:/packages/sentra-infra
      - ${HOME}/sentra-knowledge:/mnt/sentra_knowledge:rw
    networks:
      - sentrabrain-dev-net
    env_file:
      - ../services/sentra-mcp/.env

  sentra-rag-base:
    build:
      context: ../services/sentra-rag-base
      dockerfile: Dockerfile
    image: sentra-rag-base:latest
    container_name: sentra-rag-base
    restart: no
  
  sentra-rag-server:
    build:
      context: ../
      dockerfile: services/sentra-rag-server/Dockerfile
    image: sentra-rag-server:dev
    container_name: sentra-rag-server
    ports:
      - "5680:5680"   # Python debugpy
      - "9100:9100"   
    volumes:
      - ../services/sentra-rag-server:/app
      - ../packages/sentra-infra:/packages/sentra-infra
      - ${HOME}/sentra-knowledge:/mnt/sentra_knowledge:rw
    networks:
      - sentrabrain-dev-net
    env_file:
      - ../services/sentra-rag-server/.env
    depends_on:
      - sentra-vector-db

  sentra-rag-worker:
    build:
      context: ../
      dockerfile: services/sentra-rag-worker/Dockerfile
    image: sentra-rag-worker:dev
    container_name: sentra-rag-worker
    pull_policy: always
    ports:
      - "5679:5679"   # Python debugpy
      - "8081:8080"   # Metrics port
    volumes:
      - ../services/sentra-rag-worker:/app
      - ../packages/sentra-infra:/packages/sentra-infra
      - ${HOME}/sentra-knowledge:/mnt/sentra_knowledge:rw
      # - /opt/sentra-brain/knowledge:/mnt/sentra_knowledge:rw
    networks:
      - sentrabrain-dev-net
    env_file:
      - ../services/sentra-rag-worker/.env
    depends_on:
      - sentra-sql-db
      - sentra-vector-db
      - rabbitmq

  llama:
    image: ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
    container_name: llama_server
    ports:
      - "8002:8080"
    volumes:
      - /home/sysadmin/models:/models:ro
    environment:
      - LLAMA_ARG_JINJA=true
    networks:
      - sentrabrain-dev-net
  # vllm:
  #   image: vllm/vllm-openai
  #   container_name: vllm
  #   ports:
  #     - "8002:8000"  # External port 8002, internal remains 8000
  #   volumes:
  #     - D:\models:/models:ro
  #   command: >
  #     --model /models/meta-llama--Llama-3.1-8B-Instruct
  #     --dtype float16
  #     --gpu-memory-utilization 0.9
  #   networks:
  #     - sentrabrain-dev-net
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   runtime: nvidia

  sentra-sql-db:
    image: postgres:16-alpine
    container_name: sentra-sql-db
    ports:
      - "5432:5432"
    volumes:
      - sentra-sql-data:/var/lib/postgresql/data
    networks:
      - sentrabrain-dev-net
    env_file:
      - .dev.env

  sentra-nosql-db:
    image: mongo:7
    container_name: sentra-nosql-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeit
    ports:
      - "27017:27017"
    volumes:
      - sentra-nosql-data:/data/db
    networks:
      - sentrabrain-dev-net

  sentra-vector-db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: sentra-vector-db
    ports:
      - "8000:8000"
    volumes:
      - sentra-vector-data:/chroma/.chroma/index
    networks:
      - sentrabrain-dev-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: sentra
      RABBITMQ_DEFAULT_PASS: sentra
    networks:
      - sentrabrain-dev-net

volumes:
  sentra-sql-data:
  sentra-nosql-data:
  sentra-vector-data:
  prometheus-data:
  grafana-data:
  loki-data:

networks:
  sentrabrain-dev-net:
    driver: bridge
