services:
  sentra-web:
    image: sentrabrain.azurecr.io/sentra-web:latest
    container_name: sentra-web
    pull_policy: always
    ports:
      - "3100:3100"
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env

  sentra-admin:
    image: sentrabrain.azurecr.io/sentra-admin:latest
    container_name: sentra-admin
    pull_policy: always
    ports:
      - "3200:3200"
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env

  sentra-api:
    image: sentrabrain.azurecr.io/sentra-api:latest
    container_name: sentra-api
    pull_policy: always
    ports:
      - "8100:8100"
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env

  sentra-rag-base:
    image: sentrabrain.azurecr.io/sentra-rag-base:latest
    container_name: sentra-rag-base
    pull_policy: always
    networks:
      - sentrabrain-net

  sentra-rag-worker:
    image: sentrabrain.azurecr.io/sentra-rag-worker:latest
    container_name: sentra-rag-worker
    pull_policy: always
    volumes:
      - /opt/sentra-brain/knowledge:/mnt/sentra_knowledge:rw
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env
    depends_on:
      - sentra-sql-db
      - sentra-vector-db
      - rabbitmq
      - sentra-rag-base

  vllm:
    image: vllm/vllm-openai
    container_name: vllm
    ports:
      - "8002:8000"  # External port 8002, internal remains 8000
    volumes:
      - D:\models:/models:ro
    command: >
      --model /models/meta-llama--Llama-3.1-8B-Instruct
      --dtype float16
      --gpu-memory-utilization 0.9
    networks:
      - sentrabrain-dev-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  sentra-vector-db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: sentra-vector-db
    ports:
      - "8000:8000"
    volumes:
      - sentra-vector-data:/chroma/.chroma/index
    networks:
      - sentrabrain-net

  sentra-sql-db:
    image: postgres:16-alpine
    container_name: sentra-sql-db
    ports:
      - "5432:5432"
    volumes:
      - sentra-sql-data:/var/lib/postgresql/data
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env

  sentra-nosql-db:
    image: mongo:7
    container_name: sentra-nosql-db
    ports:
      - "27017:27017"
    volumes:
      - sentra-nosql-data:/data/db
    networks:
      - sentrabrain-net
    env_file:
      - .prod.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: sentra
      RABBITMQ_DEFAULT_PASS: sentra
    networks:
      - sentrabrain-net

volumes:
  sentra-sql-data:
  sentra-nosql-data:
  sentra-vector-data:

networks:
  sentrabrain-net:
    driver: bridge
