"""Add markdown fields

Revision ID: 4797f9591949
Revises: 62cc3789b6d3
Create Date: 2025-08-12 08:09:13.188323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData 


# revision identifiers, used by Alembic.
revision: str = '4797f9591949'
down_revision: Union[str, Sequence[str], None] = '62cc3789b6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('markdown_path', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('markdown_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('markdown_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('has_markdown', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    op.create_index("ix_documents_has_markdown", "documents", ["has_markdown"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_has_markdown", table_name="documents")
    op.drop_column('documents', 'has_markdown')
    op.drop_column('documents', 'markdown_hash')
    op.drop_column('documents', 'markdown_bytes')
    op.drop_column('documents', 'markdown_path')
    # ### end Alembic commands ###
