"""Add user profile fields

Revision ID: add_user_profile_fields
Revises: fceef663e3e0
Create Date: 2025-01-08 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_user_profile_fields'
down_revision: Union[str, Sequence[str], None] = 'fceef663e3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add user profile fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=False, server_default='es'))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=False, server_default='Europe/Madrid'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove user profile fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###