[project]
name = "sentra-rag"
version = "0.1.0"
description = "RAG-specific logic: embeddings, vector store, chunking"
authors = [{ name = "Juan G Carmona" }]
readme = "README.md"
requires-python = ">=3.9"

# main dependencies
dependencies = [
  "httpx",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
]

# Optional dependencies
[project.optional-dependencies]
dev = [
  "pytest==8.4.1",
  "pytest-cov==6.2.1",
  "pytest-mock==3.14.1",
  "pytest-asyncio==1.1.0",
  "debugpy==1.8.15",
]

ml = [
  "sentence-transformers==5.0.0",
  "chromadb==1.0.15",
]

[tool.setuptools]
packages = ["sentra_rag"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"