[pytest]
addopts = -v --cov=sentra_rag_worker --cov-report=term --cov-report=xml:coverage.xml
testpaths = tests

# This is needed to avoid asyncio warnings
markers =
    asyncio: mark test as asyncio to run with pytest-asyncio

[coverage:run]
branch = True
source = sentra_brain_api
